[package]
name = "bridge-proofs"
version = "0.1.0"
edition = "2021"

[dependencies]
scale-codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, optional = true, features = ["derive", "max-encoded-len"] }
ethers = "0.17.0"
webb-proposals = { path = "../proposals", default-features = false }

[dev-dependencies]
serde_json = "1.0.83"
serde = "1.0.143"
tokio = { version = "1.20.1", features = ["full"] }
hex = "0.4.3"