[package]
name = "proposal-derive"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
ethers-core = { workspace = true }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
